### ISSUE TITLE
GitHub pages is broken

### ISSUE THREAD

**Issue by kai-chu** [KTH/ci-hackathon#20]
https://kth.github.io/ci-hackathon is not found now

**Comment by Jacarte** [comment]
Yep...sorry for that, we have an issue on the automated publishing...we are working on that. I think its working now

**Comment by kai-chu** [comment]
Issue is resolved.

**Comment by tdurieux** [comment]
It is broken again

**Comment by Jacarte** [comment]
Solved. It was a problem with the GitHub Action.

**Comment by kai-chu** [comment]
Seems not stable, when I opened from my phone.  “A problem repeatedly occurred...”
