### ISSUE TITLE
How to turn off lights using the API?

### ISSUE THREAD

**Issue by tdurieux** [KTH/ci-hackathon#31]

**Comment by Jacarte** [comment]
We are implementing an abstraction to do it because right now, to get the blackout you need to command the lights one by one.  You can view a "blackout" function [here](https://github.com/KTH/ci-hackathon/blob/master/resources/emulators/lights/src/examples/traviss.py)

**Comment by tdurieux** [comment]
Thanks, I thought it would be something like this but the emulator does not accept 0 as a valid number (manual input)

**Comment by Jacarte** [comment]
> Thanks, I thought it would be something like this but the emulator does not accept 0 as a valid number (manual input)

Oh, I had not seen this bug in the emulator, thank you for the report

**Comment by tdurieux** [comment]
It is because of `!r || !g || !b` 
in 
```js
if(!r || !g || !b ||  !(0 <= r <= 255) || !(0 <= g <= 255)  || !(0 <= b <= 255) ||r*g*b < 0 ){
  alert("RGB value must be in between 0 and 255 values");
  return;
}
```
`!0` is true is js

**Comment by Jacarte** [comment]
True...on it

**Comment by Jacarte** [comment]
Done ! added new [endpoint](https://ci-lights.azurewebsites.net/help) ```blackout```
