### ISSUE TITLE
Prepare web API for DMX controller

### ISSUE THREAD

**Issue by bbaudry** [KTH/ci-hackathon#7]
Pair a raspberry Pi with a DMX controller
Embed a web server on the Pi to let hackathon participants access the controller

@christian-stj : can you add here the references for the hardware that you will acquire?

**Comment by christian-stj** [comment]
### Hardware:
- [Raspberry Pi Model B](https://www.raspberrypi.org/products/raspberry-pi-3-model-b/)
- [ENTTEC DMX USB Pro](https://www.enttec.co.uk/en/product/controls/dmx-usb-interfaces/dmx-usb-interface/)

**Comment by bbaudry** [comment]
Thanks a lot  @Jacarte and @christian-stj for this great collaborative work!

The hardware bridge is ready, as well as the emulator
https://github.com/KTH/ci-hackathon/tree/master/resources/emulators/lights

Looking forward to live tests in R1 on sept 10!
